version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=123456789
      - DATABASE_NAME=consultorio

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: consultorio
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
